# Generated by Django 4.2.1 on 2023-05-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
